name: Build DarcySnipTool EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pillow pystray pywin32 pyinstaller keyboard

      - name: Install UPX
        run: |
          choco install upx -y

      - name: Build EXE
        run: |
          python -c "from snip_tool import make_ico_file; make_ico_file()"
          pyinstaller --onefile --windowed --name DarcySnipTool --icon=darcysniptool.ico --upx-dir="C:\ProgramData\chocolatey\bin" --exclude-module numpy --exclude-module matplotlib --exclude-module scipy --exclude-module pandas --exclude-module tkinter.test snip_tool.py --clean --noconfirm

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: DarcySnipTool-Windows
          path: dist/DarcySnipTool.exe
